# Generated by Django 3.0.5 on 2020-06-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouruser', '0005_auto_20200602_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userschool',
            field=models.TextField(max_length=120, verbose_name='소속'),
        ),
    ]
