# Generated by Django 3.0.5 on 2020-06-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouruser', '0006_auto_20200602_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userschool',
            field=models.IntegerField(verbose_name='전화번호'),
        ),
    ]
