# Generated by Django 3.0.5 on 2020-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouruser', '0007_auto_20200602_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userschool',
            field=models.CharField(max_length=32, verbose_name='소속'),
        ),
    ]
